--
-- PostgreSQL database dump
--

\restrict 64qn8aJC95tbUIy7IJu1Fpdp0j83kGafLYebtNHbrmjQBH7a0wKL1gwC0fjwdQL

-- Dumped from database version 15.15
-- Dumped by pg_dump version 15.15

-- Started on 2026-09-04 03:36:55 UTC

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 215 (class 1259 OID 16397)
-- Name: categorias; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.categorias (
    id integer NOT NULL,
    nombre character varying
);


ALTER TABLE public.categorias OWNER TO admin;

--
-- TOC entry 219 (class 1259 OID 16419)
-- Name: especificaciones_aereo; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.especificaciones_aereo (
    medio_id integer NOT NULL,
    velocidad_max_mach numeric,
    techo_servicio_pies integer,
    radio_combate_millas integer,
    carga_g_maxima numeric,
    peso_max_despegue_lb integer,
    rcs_m2 numeric,
    envergadura_pies numeric,
    longitud_pies numeric
);


ALTER TABLE public.especificaciones_aereo OWNER TO admin;

--
-- TOC entry 222 (class 1259 OID 16440)
-- Name: especificaciones_armamento; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.especificaciones_armamento (
    medio_id integer NOT NULL,
    tipo_guia character varying,
    tipo_objetivo character varying,
    alcance_max_km numeric,
    velocidad_max_mach numeric,
    peso_ojiva_kg numeric,
    tecnologia_buscador character varying
);


ALTER TABLE public.especificaciones_armamento OWNER TO admin;

--
-- TOC entry 220 (class 1259 OID 16426)
-- Name: especificaciones_ew; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.especificaciones_ew (
    medio_id integer NOT NULL,
    rango_frecuencia_min_mhz numeric,
    rango_frecuencia_max_mhz numeric,
    modos_operacion character varying,
    potencia_emision_erp_kw numeric,
    capacidad_drfm boolean,
    tecnicas_jamming character varying,
    numero_objetivos_simultaneos integer
);


ALTER TABLE public.especificaciones_ew OWNER TO admin;

--
-- TOC entry 221 (class 1259 OID 16433)
-- Name: especificaciones_radar; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.especificaciones_radar (
    medio_id integer NOT NULL,
    banda_frecuencia character varying,
    alcance_deteccion_km integer,
    tipo_antena character varying,
    resolucion_distancia_m numeric,
    potencia_pico_kw numeric
);


ALTER TABLE public.especificaciones_radar OWNER TO admin;

--
-- TOC entry 216 (class 1259 OID 16404)
-- Name: fabricante; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.fabricante (
    id integer NOT NULL,
    nombre character varying,
    pais_id integer
);


ALTER TABLE public.fabricante OWNER TO admin;

--
-- TOC entry 223 (class 1259 OID 16447)
-- Name: integracion_armamento; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.integracion_armamento (
    id integer NOT NULL,
    medio_plataforma_id integer,
    medio_misil_id integer
);


ALTER TABLE public.integracion_armamento OWNER TO admin;

--
-- TOC entry 218 (class 1259 OID 16412)
-- Name: medio; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.medio (
    id integer NOT NULL,
    nombre character varying,
    modelo character varying,
    fabricante_id integer,
    categoria_id integer,
    pais_origen_id integer,
    costo_adquisicion_m_usd numeric,
    costo_operativo_hora_usd integer,
    vida_util_horas integer,
    "año_introduccion" integer,
    tripulacion_dotacion character varying,
    inventario_estimado character varying,
    capacidad_produccion_anual character varying,
    descripcion text,
    imagen_url character varying
);


ALTER TABLE public.medio OWNER TO admin;

--
-- TOC entry 217 (class 1259 OID 16411)
-- Name: medio_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.medio ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.medio_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 16452)
-- Name: operadores_medios; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.operadores_medios (
    id integer NOT NULL,
    medio_id integer,
    pais_id integer,
    tipo_relacion character varying
);


ALTER TABLE public.operadores_medios OWNER TO admin;

--
-- TOC entry 214 (class 1259 OID 16388)
-- Name: pais; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.pais (
    id integer NOT NULL,
    nombre character varying,
    continente character varying
);


ALTER TABLE public.pais OWNER TO admin;

--
-- TOC entry 226 (class 1259 OID 24578)
-- Name: usuarios; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.usuarios (
    id integer NOT NULL,
    username character varying(50) NOT NULL,
    password character varying(255) NOT NULL,
    rol character varying(20) NOT NULL
);


ALTER TABLE public.usuarios OWNER TO admin;

--
-- TOC entry 225 (class 1259 OID 24577)
-- Name: usuarios_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.usuarios ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.usuarios_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3482 (class 0 OID 16397)
-- Dependencies: 215
-- Data for Name: categorias; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.categorias (id, nombre) FROM stdin;
1	Caza
2	Bombardero
3	Misil
4	Guerra Electrónica
5	Radar
90	Alerta Temprana
91	Embarcado
92	Guerra Electrónica
93	Misil Aire-Aire
201	Aire-Aire
\.


--
-- TOC entry 3486 (class 0 OID 16419)
-- Dependencies: 219
-- Data for Name: especificaciones_aereo; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.especificaciones_aereo (medio_id, velocidad_max_mach, techo_servicio_pies, radio_combate_millas, carga_g_maxima, peso_max_despegue_lb, rcs_m2, envergadura_pies, longitud_pies) FROM stdin;
\.


--
-- TOC entry 3489 (class 0 OID 16440)
-- Dependencies: 222
-- Data for Name: especificaciones_armamento; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.especificaciones_armamento (medio_id, tipo_guia, tipo_objetivo, alcance_max_km, velocidad_max_mach, peso_ojiva_kg, tecnologia_buscador) FROM stdin;
\.


--
-- TOC entry 3487 (class 0 OID 16426)
-- Dependencies: 220
-- Data for Name: especificaciones_ew; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.especificaciones_ew (medio_id, rango_frecuencia_min_mhz, rango_frecuencia_max_mhz, modos_operacion, potencia_emision_erp_kw, capacidad_drfm, tecnicas_jamming, numero_objetivos_simultaneos) FROM stdin;
\.


--
-- TOC entry 3488 (class 0 OID 16433)
-- Dependencies: 221
-- Data for Name: especificaciones_radar; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.especificaciones_radar (medio_id, banda_frecuencia, alcance_deteccion_km, tipo_antena, resolucion_distancia_m, potencia_pico_kw) FROM stdin;
\.


--
-- TOC entry 3483 (class 0 OID 16404)
-- Dependencies: 216
-- Data for Name: fabricante; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.fabricante (id, nombre, pais_id) FROM stdin;
1	FAdeA - Fábrica Argentina de Aviones	1
2	INVAP	1
3	CITEDEF	1
4	Embraer	2
5	Avibras	2
6	Helibras	2
7	ENAER - Empresa Nacional de Aeronáutica	3
8	FAMAE - Fábricas y Maestranzas del Ejército	3
9	CIAC - Corporación de la Industria Aeronáutica	4
10	SEMAN - Servicio de Mantenimiento del Perú	5
11	Lockheed Martin	20
12	Boeing Defense, Space & Security	20
13	Northrop Grumman	20
14	RTX Corporation (Raytheon)	20
15	General Dynamics	20
16	Airbus Defence and Space	23
17	Dassault Aviation	23
20	Thales Group	23
18	BAE Systems	22
19	Leonardo S.p.A.	25
21	Saab AB	27
22	Sukhoi (UAC)	36
23	Mikoyan MiG (UAC)	36
24	Tupolev (UAC)	36
25	Chengdu Aircraft Industry Group (CAIG)	37
26	Israel Aerospace Industries (IAI)	46
27	Elbit Systems	46
\.


--
-- TOC entry 3490 (class 0 OID 16447)
-- Dependencies: 223
-- Data for Name: integracion_armamento; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.integracion_armamento (id, medio_plataforma_id, medio_misil_id) FROM stdin;
\.


--
-- TOC entry 3485 (class 0 OID 16412)
-- Dependencies: 218
-- Data for Name: medio; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.medio (id, nombre, modelo, fabricante_id, categoria_id, pais_origen_id, costo_adquisicion_m_usd, costo_operativo_hora_usd, vida_util_horas, "año_introduccion", tripulacion_dotacion, inventario_estimado, capacidad_produccion_anual, descripcion, imagen_url) FROM stdin;
\.


--
-- TOC entry 3491 (class 0 OID 16452)
-- Dependencies: 224
-- Data for Name: operadores_medios; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.operadores_medios (id, medio_id, pais_id, tipo_relacion) FROM stdin;
\.


--
-- TOC entry 3481 (class 0 OID 16388)
-- Dependencies: 214
-- Data for Name: pais; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.pais (id, nombre, continente) FROM stdin;
1	Argentina	América del Sur
2	Brasil	América del Sur
3	Chile	América del Sur
4	Colombia	América del Sur
5	Perú	América del Sur
6	Uruguay	América del Sur
7	Paraguay	América del Sur
8	Bolivia	América del Sur
9	Ecuador	América del Sur
10	Venezuela	América del Sur
11	México	América del Norte
12	Cuba	América Central y Caribe
13	Honduras	América Central y Caribe
14	Guatemala	América Central y Caribe
15	El Salvador	América Central y Caribe
16	Nicaragua	América Central y Caribe
17	Costa Rica	América Central y Caribe
18	Panamá	América Central y Caribe
19	República Dominicana	América Central y Caribe
20	Estados Unidos	América del Norte
21	Canadá	América del Norte
22	Reino Unido	Europa
23	Francia	Europa
24	Alemania	Europa
25	Italia	Europa
26	España	Europa
27	Suecia	Europa
28	Suiza	Europa
29	Países Bajos	Europa
30	Bélgica	Europa
31	Grecia	Europa
32	Noruega	Europa
33	Finlandia	Europa
34	Polonia	Europa
35	Ucrania	Europa
36	Rusia	Europa
37	China	Asia
38	India	Asia
39	Japón	Asia
40	Corea del Sur	Asia
41	Corea del Norte	Asia
42	Pakistán	Asia
43	Taiwán	Asia
44	Indonesia	Asia
45	Singapur	Asia
46	Israel	Medio Oriente
47	Turquía	Medio Oriente
48	Irán	Medio Oriente
49	Arabia Saudita	Medio Oriente
50	Emiratos Árabes Unidos	Medio Oriente
51	Egipto	África
52	Sudáfrica	África
53	Australia	Oceanía
\.


--
-- TOC entry 3493 (class 0 OID 24578)
-- Dependencies: 226
-- Data for Name: usuarios; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.usuarios (id, username, password, rol) FROM stdin;
1	admin	admin123	ADMIN
2	invitado	invitado123	VISITANTE
3	lucas	lucas1234	VISITANTE
\.


--
-- TOC entry 3499 (class 0 OID 0)
-- Dependencies: 217
-- Name: medio_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.medio_id_seq', 15, true);


--
-- TOC entry 3500 (class 0 OID 0)
-- Dependencies: 225
-- Name: usuarios_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.usuarios_id_seq', 3, true);


--
-- TOC entry 3306 (class 2606 OID 16403)
-- Name: categorias categorias_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.categorias
    ADD CONSTRAINT categorias_pkey PRIMARY KEY (id);


--
-- TOC entry 3312 (class 2606 OID 16425)
-- Name: especificaciones_aereo especificaciones_aereo_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.especificaciones_aereo
    ADD CONSTRAINT especificaciones_aereo_pkey PRIMARY KEY (medio_id);


--
-- TOC entry 3314 (class 2606 OID 16432)
-- Name: especificaciones_ew especificaciones_ew_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.especificaciones_ew
    ADD CONSTRAINT especificaciones_ew_pkey PRIMARY KEY (medio_id);


--
-- TOC entry 3318 (class 2606 OID 16446)
-- Name: especificaciones_armamento especificaciones_misil_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.especificaciones_armamento
    ADD CONSTRAINT especificaciones_misil_pkey PRIMARY KEY (medio_id);


--
-- TOC entry 3316 (class 2606 OID 16439)
-- Name: especificaciones_radar especificaciones_radar_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.especificaciones_radar
    ADD CONSTRAINT especificaciones_radar_pkey PRIMARY KEY (medio_id);


--
-- TOC entry 3308 (class 2606 OID 16410)
-- Name: fabricante fabricante_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.fabricante
    ADD CONSTRAINT fabricante_pkey PRIMARY KEY (id);


--
-- TOC entry 3320 (class 2606 OID 16451)
-- Name: integracion_armamento integracion_armamento_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.integracion_armamento
    ADD CONSTRAINT integracion_armamento_pkey PRIMARY KEY (id);


--
-- TOC entry 3310 (class 2606 OID 16418)
-- Name: medio medio_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.medio
    ADD CONSTRAINT medio_pkey PRIMARY KEY (id);


--
-- TOC entry 3322 (class 2606 OID 16458)
-- Name: operadores_medios operadores_medios_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.operadores_medios
    ADD CONSTRAINT operadores_medios_pkey PRIMARY KEY (id);


--
-- TOC entry 3302 (class 2606 OID 16396)
-- Name: pais pais_nombre_key; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.pais
    ADD CONSTRAINT pais_nombre_key UNIQUE (nombre);


--
-- TOC entry 3304 (class 2606 OID 16394)
-- Name: pais pais_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.pais
    ADD CONSTRAINT pais_pkey PRIMARY KEY (id);


--
-- TOC entry 3324 (class 2606 OID 24582)
-- Name: usuarios usuarios_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_pkey PRIMARY KEY (id);


--
-- TOC entry 3326 (class 2606 OID 24584)
-- Name: usuarios usuarios_username_key; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_username_key UNIQUE (username);


--
-- TOC entry 3331 (class 2606 OID 16479)
-- Name: especificaciones_aereo especificaciones_aereo_medio_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.especificaciones_aereo
    ADD CONSTRAINT especificaciones_aereo_medio_id_fkey FOREIGN KEY (medio_id) REFERENCES public.medio(id);


--
-- TOC entry 3332 (class 2606 OID 16484)
-- Name: especificaciones_ew especificaciones_ew_medio_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.especificaciones_ew
    ADD CONSTRAINT especificaciones_ew_medio_id_fkey FOREIGN KEY (medio_id) REFERENCES public.medio(id);


--
-- TOC entry 3334 (class 2606 OID 16494)
-- Name: especificaciones_armamento especificaciones_misil_medio_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.especificaciones_armamento
    ADD CONSTRAINT especificaciones_misil_medio_id_fkey FOREIGN KEY (medio_id) REFERENCES public.medio(id);


--
-- TOC entry 3333 (class 2606 OID 16489)
-- Name: especificaciones_radar especificaciones_radar_medio_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.especificaciones_radar
    ADD CONSTRAINT especificaciones_radar_medio_id_fkey FOREIGN KEY (medio_id) REFERENCES public.medio(id);


--
-- TOC entry 3327 (class 2606 OID 16459)
-- Name: fabricante fabricante_pais_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.fabricante
    ADD CONSTRAINT fabricante_pais_id_fkey FOREIGN KEY (pais_id) REFERENCES public.pais(id);


--
-- TOC entry 3335 (class 2606 OID 16504)
-- Name: integracion_armamento integracion_armamento_medio_misil_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.integracion_armamento
    ADD CONSTRAINT integracion_armamento_medio_misil_id_fkey FOREIGN KEY (medio_misil_id) REFERENCES public.medio(id);


--
-- TOC entry 3336 (class 2606 OID 16499)
-- Name: integracion_armamento integracion_armamento_medio_plataforma_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.integracion_armamento
    ADD CONSTRAINT integracion_armamento_medio_plataforma_id_fkey FOREIGN KEY (medio_plataforma_id) REFERENCES public.medio(id);


--
-- TOC entry 3328 (class 2606 OID 16469)
-- Name: medio medio_categoria_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.medio
    ADD CONSTRAINT medio_categoria_id_fkey FOREIGN KEY (categoria_id) REFERENCES public.categorias(id);


--
-- TOC entry 3329 (class 2606 OID 16464)
-- Name: medio medio_fabricante_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.medio
    ADD CONSTRAINT medio_fabricante_id_fkey FOREIGN KEY (fabricante_id) REFERENCES public.fabricante(id);


--
-- TOC entry 3330 (class 2606 OID 16474)
-- Name: medio medio_pais_origen_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.medio
    ADD CONSTRAINT medio_pais_origen_id_fkey FOREIGN KEY (pais_origen_id) REFERENCES public.pais(id);


--
-- TOC entry 3337 (class 2606 OID 16509)
-- Name: operadores_medios operadores_medios_medio_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.operadores_medios
    ADD CONSTRAINT operadores_medios_medio_id_fkey FOREIGN KEY (medio_id) REFERENCES public.medio(id);


--
-- TOC entry 3338 (class 2606 OID 16514)
-- Name: operadores_medios operadores_medios_pais_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.operadores_medios
    ADD CONSTRAINT operadores_medios_pais_id_fkey FOREIGN KEY (pais_id) REFERENCES public.pais(id);


-- Completed on 2026-09-04 03:36:56 UTC

--
-- PostgreSQL database dump complete
--

\unrestrict 64qn8aJC95tbUIy7IJu1Fpdp0j83kGafLYebtNHbrmjQBH7a0wKL1gwC0fjwdQL

