SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';
SET default_table_access_method = heap;

CREATE TABLE public.categorias (
    id integer NOT NULL,
    nombre character varying
);
ALTER TABLE public.categorias OWNER TO admin;

CREATE TABLE public.especificaciones_aereo (
    medio_id integer NOT NULL,
    velocidad_max_mach numeric,
    techo_servicio_pies integer,
    radio_combate_millas integer,
    carga_g_maxima numeric,
    peso_max_despegue_lb integer,
    rcs_m2 numeric,
    envergadura_pies numeric,
    longitud_pies numeric
);
ALTER TABLE public.especificaciones_aereo OWNER TO admin;

CREATE TABLE public.especificaciones_ew (
    medio_id integer NOT NULL,
    rango_frecuencia_min_mhz numeric,
    rango_frecuencia_max_mhz numeric,
    modos_operacion character varying,
    potencia_emision_erp_kw numeric,
    capacidad_drfm boolean,
    tecnicas_jamming character varying,
    numero_objetivos_simultaneos integer
);
ALTER TABLE public.especificaciones_ew OWNER TO admin;

CREATE TABLE public.especificaciones_misil (
    medio_id integer NOT NULL,
    tipo_guia character varying,
    tipo_objetivo character varying,
    alcance_max_km numeric,
    velocidad_max_mach numeric,
    peso_ojiva_kg numeric,
    tecnologia_buscador character varying
);
ALTER TABLE public.especificaciones_misil OWNER TO admin;

CREATE TABLE public.especificaciones_radar (
    medio_id integer NOT NULL,
    banda_frecuencia character varying,
    alcance_deteccion_km integer,
    tipo_antena character varying,
    resolucion_distancia_m numeric,
    potencia_pico_kw numeric
);
ALTER TABLE public.especificaciones_radar OWNER TO admin;

CREATE TABLE public.fabricante (
    id integer NOT NULL,
    nombre character varying,
    pais_id integer
);
ALTER TABLE public.fabricante OWNER TO admin;

CREATE TABLE public.integracion_armamento (
    id integer NOT NULL,
    medio_plataforma_id integer,
    medio_misil_id integer
);
ALTER TABLE public.integracion_armamento OWNER TO admin;

CREATE TABLE public.medio (
    id integer NOT NULL,
    nombre character varying,
    modelo character varying,
    fabricante_id integer,
    categoria_id integer,
    pais_origen_id integer,
    costo_adquisicion_m_usd numeric,
    costo_operativo_hora_usd integer,
    vida_util_horas integer,
    "año_introduccion" integer,
    tripulacion_dotacion character varying,
    inventario_estimado character varying,
    capacidad_produccion_anual character varying,
    descripcion text,
    imagen_url character varying
);
ALTER TABLE public.medio OWNER TO admin;

ALTER TABLE public.medio ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.medio_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.operadores_medios (
    id integer NOT NULL,
    medio_id integer,
    pais_id integer,
    tipo_relacion character varying
);
ALTER TABLE public.operadores_medios OWNER TO admin;

CREATE TABLE public.pais (
    id integer NOT NULL,
    nombre character varying,
    continente character varying
);
ALTER TABLE public.pais OWNER TO admin;

COPY public.categorias (id, nombre) FROM stdin;
1	Caza
2	Bombardero
3	Misil
4	Guerra Electrónica
5	Radar
\.

COPY public.especificaciones_aereo (medio_id, velocidad_max_mach, techo_servicio_pies, radio_combate_millas, carga_g_maxima, peso_max_despegue_lb, rcs_m2, envergadura_pies, longitud_pies) FROM stdin;
1	1.6	50000	669	9.0	70000	0.001	35.0	51.4
2	2.0	65000	932	9.0	77162	0.1	46.6	65.9
3	2.0	66000	1243	9.0	81570	0.05	44.3	68.9
4	1.8	50000	1000	9.0	54013	1.0	35.4	50.1
\.

COPY public.especificaciones_ew (medio_id, rango_frecuencia_min_mhz, rango_frecuencia_max_mhz, modos_operacion, potencia_emision_erp_kw, capacidad_drfm, tecnicas_jamming, numero_objetivos_simultaneos) FROM stdin;
\.

COPY public.especificaciones_misil (medio_id, tipo_guia, tipo_objetivo, alcance_max_km, velocidad_max_mach, peso_ojiva_kg, tecnologia_buscador) FROM stdin;
5	Activa por radar	Aéreo	180.0	4.0	18.1	Radar activo de banda Ku
\.

COPY public.especificaciones_radar (medio_id, banda_frecuencia, alcance_deteccion_km, tipo_antena, resolucion_distancia_m, potencia_pico_kw) FROM stdin;
\.

COPY public.fabricante (id, nombre, pais_id) FROM stdin;
1	Lockheed Martin	1
2	Boeing	1
3	Sukhoi	2
4	Chengdu Aircraft	3
5	Dassault Aviation	4
6	Raytheon	1
\.

COPY public.integracion_armamento (id, medio_plataforma_id, medio_misil_id) FROM stdin;
1	1	5
2	4	5
\.

COPY public.medio (id, nombre, modelo, fabricante_id, categoria_id, pais_origen_id, costo_adquisicion_m_usd, costo_operativo_hora_usd, vida_util_horas, "año_introduccion", tripulacion_dotacion, inventario_estimado, capacidad_produccion_anual, descripcion, imagen_url) FROM stdin;
1	F-35A	Lightning II	1	1	1	89.0	36000	8000	2015	1 piloto	450+	156 unidades/año	Caza de quinta generación con capacidades stealth avanzadas.	https://ejemplo.com/f35.jpg
2	Su-57	Felon	3	1	2	35.0	20000	6000	2020	1 piloto	10+	12 unidades/año	Caza de quinta generación ruso con supercruise.	https://ejemplo.com/su57.jpg
3	J-20	Chengdu J-20	4	1	3	110.0	25000	7000	2017	1 piloto	150+	20 unidades/año	Caza stealth chino de quinta generación.	https://ejemplo.com/j20.jpg
4	Rafale	Rafale F4	5	1	4	80.0	16500	7500	2001	1 piloto	200+	24 unidades/año	Caza multirrol francés de cuarta generación avanzada.	https://ejemplo.com/rafale.jpg
5	AIM-120	AMRAAM	6	3	1	1.8	\N	\N	1991	N/A	14000+	500 unidades/año	Misil aire-aire de medio alcance con guía activa por radar.	https://ejemplo.com/aim120.jpg
7	F-16	Falcon	1	1	1	30	3000	40000	1967	1	200	100	Aeronave polivalente de 4ta generacion	\N
8	TPS-78	ADCAP	1	5	1	40	500	90000	2010	1	1	1	El AN/TPS-78 ADCAP™ MMR es un radar 3D de banda S de largo alcance (240 millas náuticas / 444 km), con una velocidad de escaneo de 10 y 5 segundos, muy adecuado tanto para misiones de interceptación de control terrestre que requieren velocidades de actualización de objetivos más rápidas como para vigilancia aérea de largo alcance, incluido el seguimiento de misiles balísticos tácticos (TBM).	\N
9	IA-63	Pampa 3	3	2	1	1.3	1500	100000	1990	2	30	3	Pampa 3	\N
\.

COPY public.operadores_medios (id, medio_id, pais_id, tipo_relacion) FROM stdin;
1	1	1	Operador principal
2	1	5	Operador
3	2	2	Operador principal
4	3	3	Operador principal
5	4	4	Operador principal
6	5	1	Operador principal
\.

COPY public.pais (id, nombre, continente) FROM stdin;
1	Estados Unidos	América del Norte
2	Rusia	Europa/Asia
3	China	Asia
4	Francia	Europa
5	Reino Unido	Europa
\.

SELECT pg_catalog.setval('public.medio_id_seq', 9, true);

ALTER TABLE ONLY public.categorias ADD CONSTRAINT categorias_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.especificaciones_aereo ADD CONSTRAINT especificaciones_aereo_pkey PRIMARY KEY (medio_id);
ALTER TABLE ONLY public.especificaciones_ew ADD CONSTRAINT especificaciones_ew_pkey PRIMARY KEY (medio_id);
ALTER TABLE ONLY public.especificaciones_misil ADD CONSTRAINT especificaciones_misil_pkey PRIMARY KEY (medio_id);
ALTER TABLE ONLY public.especificaciones_radar ADD CONSTRAINT especificaciones_radar_pkey PRIMARY KEY (medio_id);
ALTER TABLE ONLY public.fabricante ADD CONSTRAINT fabricante_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.integracion_armamento ADD CONSTRAINT integracion_armamento_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.medio ADD CONSTRAINT medio_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.operadores_medios ADD CONSTRAINT operadores_medios_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.pais ADD CONSTRAINT pais_nombre_key UNIQUE (nombre);
ALTER TABLE ONLY public.pais ADD CONSTRAINT pais_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.especificaciones_aereo ADD CONSTRAINT especificaciones_aereo_medio_id_fkey FOREIGN KEY (medio_id) REFERENCES public.medio(id);
ALTER TABLE ONLY public.especificaciones_ew ADD CONSTRAINT especificaciones_ew_medio_id_fkey FOREIGN KEY (medio_id) REFERENCES public.medio(id);
ALTER TABLE ONLY public.especificaciones_misil ADD CONSTRAINT especificaciones_misil_medio_id_fkey FOREIGN KEY (medio_id) REFERENCES public.medio(id);
ALTER TABLE ONLY public.especificaciones_radar ADD CONSTRAINT especificaciones_radar_medio_id_fkey FOREIGN KEY (medio_id) REFERENCES public.medio(id);
ALTER TABLE ONLY public.fabricante ADD CONSTRAINT fabricante_pais_id_fkey FOREIGN KEY (pais_id) REFERENCES public.pais(id);
ALTER TABLE ONLY public.integracion_armamento ADD CONSTRAINT integracion_armamento_medio_misil_id_fkey FOREIGN KEY (medio_misil_id) REFERENCES public.medio(id);
ALTER TABLE ONLY public.integracion_armamento ADD CONSTRAINT integracion_armamento_medio_plataforma_id_fkey FOREIGN KEY (medio_plataforma_id) REFERENCES public.medio(id);
ALTER TABLE ONLY public.medio ADD CONSTRAINT medio_categoria_id_fkey FOREIGN KEY (categoria_id) REFERENCES public.categorias(id);
ALTER TABLE ONLY public.medio ADD CONSTRAINT medio_fabricante_id_fkey FOREIGN KEY (fabricante_id) REFERENCES public.fabricante(id);
ALTER TABLE ONLY public.medio ADD CONSTRAINT medio_pais_origen_id_fkey FOREIGN KEY (pais_origen_id) REFERENCES public.pais(id);
ALTER TABLE ONLY public.operadores_medios ADD CONSTRAINT operadores_medios_medio_id_fkey FOREIGN KEY (medio_id) REFERENCES public.medio(id);
ALTER TABLE ONLY public.operadores_medios ADD CONSTRAINT operadores_medios_pais_id_fkey FOREIGN KEY (pais_id) REFERENCES public.pais(id);